# Generated by Django 4.2 on 2023-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projrct_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('person', models.CharField(max_length=16, verbose_name='负责人')),
                ('path', models.CharField(max_length=64, verbose_name='脚本路径')),
                ('upload_date', models.DateField(verbose_name='上传时间')),
                ('change_date', models.DateField(blank=True, null=True, verbose_name='最近一次更改时间')),
                ('remarks', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目信息表',
                'db_table': 'projrct_info',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_nub', models.AutoField(primary_key=True, serialize=False, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('reg_date', models.DateField(verbose_name='注册时间')),
                ('status', models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态')),
                ('limits', models.CharField(choices=[(3, '管理员'), (1, '普通用户'), (4, '超级管理员'), (2, '中级用户')], max_length=16, verbose_name='账号权限')),
                ('change_pwd_date', models.DateField(verbose_name='最近一次修改密码时间')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user_info',
            },
        ),
    ]
