# Generated by Django 4.2 on 2023-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projrct_info',
            name='path',
        ),
        migrations.AddField(
            model_name='projrct_info',
            name='project_file',
            field=models.FileField(default='1', max_length=128, upload_to='project_file/', verbose_name='脚本路径'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(1, '普通用户'), (2, '中级用户'), (3, '管理员'), (4, '超级管理员')], max_length=16, verbose_name='账号权限'),
        ),
    ]
