# Generated by Django 4.2 on 2023-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_alter_projrct_info_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(2, '中级用户'), (4, '超级管理员'), (3, '管理员'), (1, '普通用户')], max_length=16, verbose_name='账号权限'),
        ),
    ]
