# Generated by Django 4.2 on 2023-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0004_alter_user_info_limits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projrct_info',
            new_name='project_info',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(4, '超级管理员'), (2, '中级用户'), (1, '普通用户'), (3, '管理员')], max_length=16, verbose_name='账号权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态'),
        ),
    ]
