# Generated by Django 4.2 on 2023-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0008_alter_user_info_limits_alter_user_info_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='note_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_name', models.CharField(max_length=32, verbose_name='笔记名称')),
                ('person', models.CharField(max_length=16, verbose_name='负责人')),
                ('note_file', models.FileField(upload_to='note_file/%Y/%m/%d/', verbose_name='笔记路径')),
                ('upload_date', models.DateField(verbose_name='上传时间')),
                ('remarks', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '笔记管理表',
                'db_table': 'note_info',
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(2, '超级管理员'), (1, '普通用户'), (3, '全部')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(2, '超级管理员'), (1, '普通用户')], max_length=16, verbose_name='账号权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态'),
        ),
    ]
