# Generated by Django 4.2 on 2023-04-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0009_note_info_alter_menuitem_auth_alter_user_info_limits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yunpan_first',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=32, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型')),
                ('person', models.CharField(blank=True, max_length=32, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '云盘一层模型',
                'db_table': 'yunpan_first',
            },
        ),
        migrations.CreateModel(
            name='yunpan_second',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=32, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型')),
                ('person', models.CharField(blank=True, max_length=32, verbose_name='上传人')),
                ('ParentID_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.yunpan_first', verbose_name='一级关联')),
            ],
            options={
                'verbose_name': '云盘二层模型',
                'db_table': 'yunpan_second',
            },
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(1, '正常'), (2, '失效')], max_length=16, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='yunpan_third',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=32, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型')),
                ('person', models.CharField(blank=True, max_length=32, verbose_name='上传人')),
                ('ParentID_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.yunpan_first', verbose_name='一级关联')),
                ('ParentID_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.yunpan_second', verbose_name='二级关联')),
            ],
            options={
                'verbose_name': '云盘三层模型',
                'db_table': 'yunpan_third',
            },
        ),
    ]
