# Generated by Django 4.2 on 2023-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0010_yunpan_first_yunpan_second_alter_user_info_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yunpan_second',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='second_file/%Y/%m/%d/', verbose_name='二级文件路径'),
        ),
        migrations.AddField(
            model_name='yunpan_third',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='third_file/%Y/%m/%d/', verbose_name='三级文件路径'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(3, '全部'), (2, '超级管理员'), (1, '普通用户')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='yunpan_first',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_second',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_third',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
    ]
