# Generated by Django 4.2 on 2023-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0011_yunpan_second_file_yunpan_third_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yunpan_first',
            name='file_type_2',
            field=models.CharField(default=1, max_length=32, verbose_name='详细文件类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yunpan_second',
            name='file_type_2',
            field=models.CharField(default=1, max_length=32, verbose_name='详细文件类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yunpan_third',
            name='file_type_2',
            field=models.CharField(default=1, max_length=32, verbose_name='详细文件类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(1, '普通用户'), (2, '超级管理员'), (3, '全部')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(1, '普通用户'), (2, '超级管理员')], max_length=16, verbose_name='账号权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(1, '正常'), (2, '失效')], max_length=16, verbose_name='状态'),
        ),
    ]
