# Generated by Django 4.2 on 2023-05-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0012_yunpan_first_file_type_2_yunpan_second_file_type_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yunpan_third',
            name='ParentID_2',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(3, '全部'), (1, '普通用户'), (2, '超级管理员')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='yunpan_third',
            name='ParentID_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.yunpan_second', verbose_name='二级关联'),
        ),
    ]
