# Generated by Django 4.2 on 2023-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0013_remove_yunpan_third_parentid_2_alter_menuitem_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(1, '普通用户'), (3, '全部'), (2, '超级管理员')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='yunpan_first',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_second',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_third',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
    ]
