# Generated by Django 4.2 on 2023-05-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0014_alter_menuitem_auth_alter_user_info_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='number',
            field=models.CharField(default='13722222222', max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(3, '全部'), (1, '普通用户'), (2, '超级管理员')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_nub',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
