# Generated by Django 4.2 on 2023-05-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0017_alter_menuitem_auth_alter_user_info_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note_info',
            name='person_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.user_info', verbose_name='上传人关联ID'),
        ),
        migrations.AddField(
            model_name='project_info',
            name='person_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.user_info', verbose_name='上传人关联ID'),
        ),
        migrations.AddField(
            model_name='yunpan_first',
            name='person_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.user_info', verbose_name='上传人关联ID'),
        ),
        migrations.AddField(
            model_name='yunpan_second',
            name='person_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.user_info', verbose_name='上传人关联ID'),
        ),
        migrations.AddField(
            model_name='yunpan_third',
            name='person_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManagement.user_info', verbose_name='上传人关联ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(2, '超级管理员'), (3, '全部'), (1, '普通用户')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(2, '超级管理员'), (1, '普通用户')], max_length=16, verbose_name='账号权限'),
        ),
        migrations.AlterField(
            model_name='yunpan_first',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_second',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_third',
            name='file_type',
            field=models.CharField(choices=[(1, '文件夹'), (2, '文件')], max_length=32, verbose_name='文件类型'),
        ),
    ]
