# Generated by Django 4.2 on 2023-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0018_note_info_person_id_project_info_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(1, '普通用户'), (2, '超级管理员'), (3, '全部')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='limits',
            field=models.CharField(choices=[(1, '普通用户'), (2, '超级管理员')], max_length=16, verbose_name='账号权限'),
        ),
        migrations.AlterField(
            model_name='yunpan_first',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_second',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='yunpan_third',
            name='file_type',
            field=models.CharField(choices=[(2, '文件'), (1, '文件夹')], max_length=32, verbose_name='文件类型'),
        ),
    ]
