# Generated by Django 4.2 on 2023-07-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0020_alter_menuitem_auth_alter_user_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='auth',
            field=models.CharField(choices=[(3, '全部'), (1, '普通用户'), (2, '超级管理员')], default=3, max_length=16, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='status',
            field=models.CharField(choices=[(2, '失效'), (1, '正常')], max_length=16, verbose_name='状态'),
        ),
    ]
