# Generated by Django 4.2 on 2023-07-03 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='组ID')),
                ('group_name', models.CharField(max_length=64, verbose_name='组名')),
                ('group_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user_group',
            },
        ),
        migrations.CreateModel(
            name='NewUserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('user_num', models.CharField(max_length=16, verbose_name='用户号码')),
                ('user_passwd', models.CharField(max_length=64, verbose_name='用户密码')),
                ('user_level', models.CharField(choices=[('1', '高级管理员'), ('2', '组管理员'), ('3', '普通用户')], default='3', max_length=1, verbose_name='用户类型')),
                ('user_his_passwd', models.CharField(blank=True, max_length=254, null=True, verbose_name='历史密码')),
                ('user_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('change_passwd_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近一次修改密码时间')),
                ('user_group_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.usergroup', verbose_name='关联组')),
            ],
            options={
                'db_table': 'new_user_info',
            },
        ),
        migrations.CreateModel(
            name='FolderBook',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件夹ID')),
                ('folder_name', models.CharField(max_length=128, verbose_name='文件夹名')),
                ('folder_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('folder_fk_id', models.ForeignKey(default='first', on_delete=django.db.models.deletion.CASCADE, to='newyunpan.folderbook', verbose_name='文件上级关联')),
                ('folder_group_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.usergroup', verbose_name='关联组')),
                ('folder_user_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.newuserinfo', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'folder_book',
            },
        ),
        migrations.CreateModel(
            name='FileBook',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件ID')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file_create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('file_folder_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.folderbook', verbose_name='关联文件夹')),
                ('file_group_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.usergroup', verbose_name='关联组')),
                ('file_user_id', models.ForeignKey(default='Unknown', on_delete=models.SET('Unknown'), to='newyunpan.newuserinfo', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'File_book',
            },
        ),
    ]
