# Generated by Django 4.2 on 2023-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyunpan', '0003_alter_filebook_file_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebook',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='newYunPan/%Y/%m/%d/', verbose_name='文件路径'),
        ),
    ]
