# Generated by Django 4.2 on 2023-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyunpan', '0004_filebook_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebook',
            name='file_type',
            field=models.CharField(blank=True, default='unknown', max_length=32, null=True, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='file_path',
            field=models.FileField(default='unknown', upload_to='newYunPan/%Y/%m/%d/', verbose_name='文件路径'),
        ),
    ]
