# Generated by Django 4.2 on 2023-07-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newyunpan', '0006_filebook_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebook',
            name='file_type',
            field=models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='文件类型'),
        ),
    ]
